defaults:
  run:
    shell: bash
jobs:
  build_and_test:
    env:
      CLASSPATH: ${{ github.workspace }}/flatbuffers/java
      DDLOG_TEST_PROGRESS: 1
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      run: echo "Build triggered by GitHub event ${GITHUB_EVENT_NAME}"
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      run: echo "${LOCALAPPDATA}"
    - continue-on-error: true
      run: echo "${HOME}/.local/bin" >> "${GITHUB_PATH}"
    - continue-on-error: true
      run: echo "${HOME}/.cargo/bin" >> "${GITHUB_PATH}"
    - continue-on-error: true
      run: echo "${PATH}"
    - continue-on-error: true
      run: echo "DIST_NAME=ddlog-${GITHUB_REF#refs/tags/}-$(date +'%Y%m%d%H%M%S')-${{
        runner.os }}" >> $GITHUB_ENV
    - continue-on-error: true
      name: Install FlatBufs
      run: ./tools/install-flatbuf.sh
    - continue-on-error: true
      if: ${{ runner.os == 'Windows' }}
      name: Run path test
      run: stack --no-terminal test --ta '-p path'
    - continue-on-error: true
      if: ${{ runner.os != 'Windows' }}
      name: Run tutorial test
      run: stack --no-terminal test --ta '-p tutorial'
    - continue-on-error: true
      name: Install ddlog executables
      run: stack --no-terminal install
    - continue-on-error: true
      if: ${{ github.event_name == 'release'  &&  runner.os == 'macOS' }}
      name: Install coreutils on MacOS
      run: brew install coreutils
    - continue-on-error: true
      if: ${{ github.event_name == 'release' }}
      name: Build distro
      run: ./build_distro.sh
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: ${{ github.event_name == 'release' }}
      name: Upload distro
      uses: alexellis/upload-assets@0.3.0
      with:
        asset_paths: '["./${{ env.DIST_NAME }}.tar.gz"]'
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
name: CI
on:
  repository_dispatch:
    types: trigger-ga___main.yml
